### ISSUE TITLE
autoindent no longer working

### ISSUE THREAD

**Issue by hkhanna** [gavocanov/vim-js-indent#4]
This plugin appears to have changed the behavior of `set autoindent`. If I select some javascript in visual mode and press `=`, everything will correctly indent. But the correct indentation no longer happens on the fly as I'm typing as it did prior to when I installed vim-js-indent.

If this is in the intended behavior, I'm happy to close the issue, but wanted to make sure this wasn't a bug, as proper indentation will now require an extra step.

**Comment by gavocanov** [comment]
Should be fixed now by reverting #3 which was more or less a test to see if another upstream was working better.

Sry for the inconvenience.
