### ISSUE TITLE
Semicolon-less style

### ISSUE THREAD

**Issue by nicknikolov** [gavocanov/vim-js-indent#6]
Hey dude!
Thanks for making this. 
I wonder if it would be reasonable to ask for semicolon-less style a la Standard. I think [this library ](https://github.com/jiangmiao/simple-javascript-indenter)supports it but obvioulsy I would prefer to stick with yours since it's maintained and it seems you support ES6 and so on.
Thanks

**Comment by gavocanov** [comment]
Hi,
I don't use this anymore and do not have time ATM to take care of this stuff, will accept PR's tho.
I'm using now a pretty plain JS config, nothing fancy and everything works really well,
config:

``` vim
Plug 'pangloss/vim-javascript', { 'for': ['javascript', 'javascript.jsx'] }
Plug 'mxw/vim-jsx', { 'for': ['javascript', 'javascript.jsx'] }
```

example:

``` javascript
var a = 1
const b = {
    test: 111,
    test2: function(p1) {
        console.log(p1)
        if (true) {
            console.log('ok')
            return
        }
        return
    },
    test3(p2) {
        console.log(p2)
    },
    test4: p3 => console.log(p3)
}
console.log(a)
console.log(b.test2('a1'))
console.log(b.test3('a2'))
console.log(b.test3('a3'))
```

If I remember correctly the initial necessity for this plugin was some problems with the combination of [yajs](https://github.com/othree/yajs.vim) and the [jsx plugin](https://github.com/mxw/vim-jsx), by using just [pangloss JS plugin](https://github.com/pangloss/vim-javascript) I'm having no problems at all now and all the new ES stuff just works, and from the example it seems to me that semicolon-less style looks just fine to.

Yajs was kind of nice on the eyes but was getting slower and slower for me after every update, and the colouring was not much consistent IMHO.

Hope this helps.

**Comment by nicknikolov** [comment]
Thanks for replying. Will try out your config.
