### ISSUE TITLE
variable format 

### ISSUE THREAD

**Issue by newby1** [gavocanov/vim-js-indent#7]
now ,Code is as follows：

> var gulp = require('gulp'),
> del = require('del'),
> path = require('path');

expect：

> var gulp = require('gulp'), 
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; del = require('del'),
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; path = require('path');

can you help me ?

**Comment by gavocanov** [comment]
Hi!

As stated in the `readme` :

``` vim
Plug 'pangloss/vim-javascript', { 'for': ['javascript', 'javascript.jsx'] }
Plug 'mxw/vim-jsx', { 'for': ['javascript', 'javascript.jsx'] }
```

That's what I use now and everything is great, I can only suggest to try that, ATM I do not have time to deal with issues, sry.
